name: Bug Report
description: Report a bug in Helios
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - VS Code Extension
        - Python Server
        - Installation/Setup
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. Windows 11, macOS 13, Ubuntu 22.04]
        - VS Code Version: [e.g. 1.85.0]
        - Python Version: [e.g. 3.10.5]
        - Helios Version: [e.g. 0.1.0]
        - Node.js Version: [e.g. 18.17.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      placeholder: Paste error messages, stack traces, or log output here
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context about the problem
      placeholder: Screenshots, configuration files, or other relevant information