name: Feature Request
description: Suggest a new feature or enhancement for Helios
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving Helios! Please describe the feature you'd like to see.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What's the current limitation?
      placeholder: "Currently, when I try to..., I face the issue that..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working.
      placeholder: "The feature could work by..."
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of Helios would this feature enhance?
      options:
        - Code Completion
        - Chat Interface
        - Model Management
        - Performance
        - User Interface
        - Configuration
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried..., but it doesn't work because..."

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be helpful.
      placeholder: |
        1. When working on...
        2. While debugging...
        3. During code review...

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: |
        If you have technical insights about implementation:
        - API changes needed
        - UI/UX considerations
        - Performance implications
      placeholder: "Technical considerations..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to write documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: This feature aligns with Helios's goal of being a local-first code assistant
          required: true
